= Home Computer Homelab Documentation using Red Hat Tech Writing Style Guide Edition


:REBUILT: Tuesday, July 18, 2023

== Introduction

This document is a step-by-step guide on how to set up a home computer homelab using  OPENSHIFT Single Node Installer (SNO). 

This homelab will consist of a OPENSHIFT SNO host that will run a default setup.

== Prerequisites

* Desktop or Laptop
* Internet connectivity
* Red Hat Account


== Hardware Requirements

To create a Openshift SNO in you homelab, you will need the following hardware:

* A desktop or laptop computer:: 6vCPU, at least 32 GB of RAM, and 2 Drives, 1 small drive to install Openshift and a large hard drive to use as LVM (Storage)
* A network switch
* Ethernet cables to connect the computer and the switch.

== Openshift SNO Installation

1. Open your browser and go to console.redhat.com
2. Click on "Red Hat OpenShift" or In the top menu, click Services, Containers, Create Cluster
3. Then click on Datacenter middle tab, Under the Assisted Installer and Click Create Cluster
4. Which will being you to the "Install OpenShift with the Assisted Installer" page
* Set Your Clustername, In this example I am useing bowcaster.
* Set your Base Domain, In this example I am using home.arpa. I  am using RFC 8375 https://www.rfc-editor.org/rfc/rfc8375.html
* Choose what version of Openshift to install. At the time of writting the current version on openshift is 4.13.4
* CPU Architecture, I am leaving as the default x86_64
* Check the box that says "Install single node OpenShift (SNO)"
* Uncheck Edit pull secrect
* Incheck Incluse customr manifests
* Choose for your homelab if you want to use DHCP or Static IP, bridges, bonds
* uncheck the Encryption of installation disk
* Click "Next: at the bottom of the page.







[NOTE]
====
Text for note.
====

[IMPORTANT]
====
Text for IMPORTANT.
====

[WARNING]
====
Text for WARNING.
====

[TIP]
====
Text for TIP.
====


== Prerequisites

* The passive voice might be appropriate for a prerequisite that is not completed by the current user. For example, having a configuration enabled by a system admin.

* Avoid using imperative formations.

* Use parallel language when you write prerequisites. For example, if one bullet is a complete sentence, write the other bullets as complete sentences. But one bullet can be passive voice and another active voice.

== Short descriptions / abstract

This description is usually at least 2-3 sentences long, and you can scan it in a few seconds. It exists between the title and the main content, connecting them and providing context and disambiguation.

Follow these guidelines when writing short descriptions:

* Include user intent:

** What users must do. This content is similar to what is in the title but should not just repeat the same information.

** Why users must complete an action. You must build from the information in the title. This content helps users understand why completing an action is important or beneficial to them.

== User-replaced values

A user-replaced value, also known as a replaceable or variable value, is a value that the user must replace with a value that is relevant for their situation. User-replaced values are often found in places such as code blocks, file paths, and commands.

Use descriptive names for user-replaced values and follow this general format: <value_name>.

Ensure that user-replaced values have the following characteristics:

* Surrounded by angle brackets (< >)

* Separated by underscores (_) for multi-word values

* Lowercase, unless the rest of the related text is uppercase or another capitalization scheme

* Italicized

* If the user-replaced value is referencing a value in code or in a command that is normally monospace, also use monospace for the user-replaced value

Create an Ansible inventory file that is named `/_<path>_/inventory/hosts`.

To italicize a user-replaced value in a code block, you must add an attribute to apply text formatting, such as subs="+quotes" or subs="normal", to the attribute list of the code block.

[subs="+quotes"]
----
$ oc describe node __<node_name>__
----

For XML code blocks, see the guidance on user-replaced values for XML.

[source,xml,subs="+quotes"]
----
<ipAddress>__${ip_address}__</ipAddress>
----

Example AsciiDoc: Cross-reference
For more information about <topic>, see xref:<link>[<link_text>].

Example AsciiDoc: External link
For more information about <topic>, see link:<link>[<link_text>].

= Glossary

== Terms and Conventions

The following terms and conventions are used throughout this document:

Attribute: A parameter passed to the Asciidoc processor that modifies the behavior or appearance of the output.
Attribute reference: A reference to an attribute value using the syntax {attribute-name}. This can be used to dynamically insert values into the output.
Cross-reference: A reference to another part of the same document using the syntax <<anchor>>. The anchor is defined using the [[anchor]] syntax.
Link: A reference to another document or website using the syntax link:text[title]. The text is the URL or file path, and the title is optional.
Footnote: A reference to additional information placed at the bottom of a page using the syntax footnote:[text]. The text is the content of the footnote.
